---
- name: install httpd packages and list git configs   
  hosts: all
  remote_user: root  
  become: yes add
  tasks:   
  - name: Install apache httpd   
    apt:        
      name: apache2        
      state: present    
  - name: Read all values from git config      
    community.general.git_config:        
    list_all: yes        
    scope: global

